name: Deploy Frontend

on:
  push:
    paths:
      - "frontend/**"
    branches:
      - feature/todo-app

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Frontend
        run: |
          cd frontend/todos
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-todos .
          
      - name: Push Frontend
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-todos:latest

  pull-and-run:
    name: Pull and run image
    needs: build-and-deploy-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Frontend to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker stop frontend-todos || true && docker rm frontend-todos || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/frontend-todos
            docker run -d -p 80:80 --name frontend-todos ${{ secrets.DOCKER_USERNAME }}/frontend-todos
