name: Deploy Backend

on:
  push:
    paths:
      - "backend/**"
    branches:
      - feature/todo-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build BE image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-todos ./backend

      - name: Push image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-todos:latest
  pull-and-run:
    name: Pull and run image
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "${{ secrets.BACKEND_ENV_FILE }}" > .env
            CONTAINER=$(docker ps -q --filter "publish=8080")
            if [ ! -z "$CONTAINER" ]; then
              echo "Stopping container using port 8080: $CONTAINER"
              docker stop $CONTAINER
              docker rm $CONTAINER
            fi
            docker pull ${{ secrets.DOCKER_USERNAME }}/backend-todos
            docker stop backend-todos || true
            docker rm backend-todos || true
            docker run --env-file .env -p 8080:3001 -d ${{ secrets.DOCKER_USERNAME }}/backend-todos
