name: Deploy Backend

on:
  push:
    paths:
      - "backend/**"
      - "frontend/**"
    branches:
      - feature/todo-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build BE image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-todos ./backend
      - name: Build FE image
        run: |
          cd frontend/todos
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-todos .
          docker build \
            --build-arg VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }} \
            -t ${{ secrets.DOCKER_USERNAME }}/frontend-todos .

      - name: Push BE image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-todos:latest
      - name: Push FE image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-todos:latest

  pull-and-run:
    name: Pull and run image
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "${{ secrets.BACKEND_ENV_FILE }}" > .env
          
            if docker ps -a --format '{{.Names}}' | grep -Eq '^backend-todos$'; then
              echo "Stopping and removing existing backend-todos container..."
              docker stop backend-todos || true
              docker rm backend-todos || true
            fi
            docker pull ${{ secrets.DOCKER_USERNAME }}/backend-todos
            docker run --env-file .env -p 8080:3001 -d ${{ secrets.DOCKER_USERNAME }}/backend-todos

            docker stop frontend-todos || true && docker rm frontend-todos || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/frontend-todos
            docker run -d -p 8081:80 --name frontend-todos ${{ secrets.DOCKER_USERNAME }}/frontend-todos